### ISSUE TITLE
Shouldn't there be scalar comparison?

### ISSUE THREAD

**Issue by ikirill** [jwmerrill/PowerSeries.jl#10]
I think that `series(c0, c1 ...) < x`, for a scalar x, should evaluate to `c0 < x`, which is what I expect when I'm using a PowerSeries to differentiate a function that has branches in its body.

**Comment by jwmerrill** [comment]
I had some initial anxiety about the correct ordering semantics of PowerSeries, but this seems reasonable to me.

Want to submit a PR? I think it should be reasonably simple to add.

**Comment by ikirill** [comment]
> I had some initial anxiety about the correct ordering semantics of PowerSeries, but this seems reasonable to me.

In principle, by the same logic, two series should be compared by their constant terms.
